import {useEffect,useState} from 'react';
import {Cloud,CloudRain,CloudSun,CloudFog,CloudLightning,Sun,Moon,Snowflake,Pause,Play,ArrowUpRight,RotateCcw} from 'lucide-react';
import PixelScene from './PixelScene';
import {nyParts,nyDateKey,seasonFor,skyFor,weatherLabel,availableHours,lightFor,NYC_TIMEZONE,type Weather} from '../data/weather';
const timeLabel=(time:number)=>new Date(time*1000).toLocaleTimeString('en-US',{timeZone:NYC_TIMEZONE,hour:'numeric',minute:'2-digit',timeZoneName:'short'});
const dayLabel=(time:number)=>new Date(time*1000).toLocaleDateString('en-US',{timeZone:NYC_TIMEZONE,weekday:'short',month:'short',day:'numeric'});
export default function CityWindow(){
 const [weather,setWeather]=useState<Weather|null>(null);const [weatherError,setWeatherError]=useState(false);const [now,setNow]=useState(new Date());const [selectedTime,setSelectedTime]=useState<number|null>(null);const [paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{let disposed=false;const controller=new AbortController();async function load(){try{const r=await fetch('/api/weather',{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)])});if(!r.ok)throw new Error();const value=await r.json();if(typeof value.temperature!=='number'||typeof value.code!=='number'||typeof value.observedAt!=='number'||typeof value.fetchedAt!=='number'||!Array.isArray(value.hourly)||!Array.isArray(value.days))throw new Error();if(!disposed){setWeather(value);setWeatherError(false);}}catch{if(!disposed)setWeatherError(true);}}
 const initial=setTimeout(()=>void load(),0);const clock=setInterval(()=>setNow(new Date()),30000);const refresh=setInterval(()=>{if(document.visibilityState==='visible')void load();},600000);return()=>{disposed=true;controller.abort();clearTimeout(initial);clearInterval(clock);clearInterval(refresh);};},[]);
 const nowSeconds=now.getTime()/1000;const stale=!!weather&&(nowSeconds-weather.fetchedAt>1800||nowSeconds-weather.observedAt>10800);const usable=weather&&!weatherError&&!stale?weather:null;
 const hours=availableHours(usable,nowSeconds);const chosen=hours.find(h=>h.time===selectedTime);const forecast=!!chosen;const moment=chosen?.time??nowSeconds;const date=nyDateKey(moment);const today=nyDateKey(nowSeconds);const dates=usable?[...new Set([today,...hours.map(h=>nyDateKey(h.time))])]:[];
 const dayTimes=[...(date===today?[nowSeconds]:[]),...hours.filter(h=>nyDateKey(h.time)===date).map(h=>h.time)];const hourIndex=chosen?Math.max(0,dayTimes.indexOf(chosen.time)):0;
 const reading=chosen??usable;const parts=nyParts(new Date(moment*1000));const season=seasonFor(parts.month);const sky=reading?skyFor(reading.code):'Cloudy';const solarDay=usable?.days.find(d=>d.date===date);const light=lightFor(moment,reading?.isDay??(parts.hour>=7&&parts.hour<19),solarDay);const shownTime=new Date(moment*1000).toLocaleTimeString('en-US',{timeZone:NYC_TIMEZONE,hour:'2-digit',minute:'2-digit',hour12:false});
 function chooseHour(index:number){const time=dayTimes[index];setSelectedTime(time===nowSeconds?null:time??null);}
 function backToNow(){setSelectedTime(null);setNow(new Date());requestAnimationFrame(()=>document.querySelector('.forecast-days')?.scrollTo({left:0,behavior:'auto'}));}
 const condition=reading?weatherLabel(reading.code):weatherError||stale?'Weather unavailable':'Checking the weather';
 function chooseDay(next:string){if(next===date)return;const options=hours.filter(h=>nyDateKey(h.time)===next);const previousHour=parts.hour;setSelectedTime((options.find(h=>nyParts(new Date(h.time*1000)).hour===previousHour)??options[0])?.time??null);}
 return <><div className="project-heading"><div><h2>New York, Illustrated<span className="heading-dot">.</span></h2><p className="project-description">The city’s weather, one pixel at a time.</p></div><button className="outline-button back-to-now" onClick={backToNow} disabled={!forecast}><RotateCcw size={13}/> Back to now</button></div>
 <div className="window-workbench"><div className="window-frame"><div className="map-toolbar"><span><span className={`status-dot ${!reading?'offline':forecast?'amber':''}`}/> {!reading?(weatherError||stale?'WEATHER UNAVAILABLE':'CHECKING NYC WEATHER'):forecast?'HOURLY FORECAST':'NEW YORK NOW'}</span><button className="text-button" onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?<Play size={12}/>:<Pause size={12}/>} {paused?'RESUME':'PAUSE'}</button></div><PixelScene season={season} sky={sky} light={light} paused={paused}/><div className="window-caption"><span>{forecast&&chosen?`${dayLabel(moment).toUpperCase()} / ${timeLabel(moment).toUpperCase()}`:'MANHATTAN / FROM THE EAST RIVER'}</span><span>NYC / {season.toUpperCase()}</span></div>{<div className="forecast-day-picker"><div className="forecast-days-heading"><p className="eyebrow">CHOOSE A DAY</p><span>DAILY HIGH / LOW · °F</span></div><div className="forecast-days" role="group" aria-label="Forecast day">{dates.map(d=>{const firstTime=d===today?nowSeconds:hours.find(h=>nyDateKey(h.time)===d)!.time;const summary=usable?.days.find(day=>day.date===d);const code=summary?.code;const sky=code==null?'unknown':skyFor(code).toLowerCase();return <button key={d} className={`forecast-day-card sky-${sky}`} aria-pressed={d===date} aria-label={`Forecast for ${dayLabel(firstTime)}`} onClick={()=>chooseDay(d)}><strong>{new Date(firstTime*1000).toLocaleDateString('en-US',{timeZone:NYC_TIMEZONE,weekday:'short'})}</strong><small>{new Date(firstTime*1000).toLocaleDateString('en-US',{timeZone:NYC_TIMEZONE,month:'short',day:'numeric'})}</small><span className="forecast-card-icon" aria-hidden="true"><ForecastIcon code={code}/></span><span className="forecast-card-condition">{code==null?'Unavailable':weatherLabel(code)}</span><span className="forecast-card-temperatures"><span aria-label="Daily high">{summary?.high==null?'—':`${summary.high}°`}</span><span aria-label="Daily low">{summary?.low==null?'—':`${summary.low}°`}</span></span></button>;})}</div>{!dates.length&&<p className="window-note">No forecast days are available right now.</p>}</div>}</div>
 <aside className="window-sidebar"><p className="eyebrow">{forecast?'THE VIEW AHEAD':'OUTSIDE THE WINDOW'}</p><div className="window-clock">{shownTime}<span>{dayLabel(moment)} / {forecast?'FORECAST':'NEW YORK'}</span></div><div className="weather-summary">{sky==='Rain'||sky==='Storm'?<CloudRain size={27}/>:sky==='Snow'?<Snowflake size={27}/>:sky==='Cloudy'||sky==='Fog'?<Cloud size={27}/>:light==='night'?<Moon size={27}/>:<Sun size={27}/>}<div><strong>{reading?`${reading.temperature}°F · `:''}{condition}</strong><span>{season} / {light==='night'?'After dark':light==='dawn'?'Morning light':light==='dusk'?'Evening light':'Daylight'}</span></div></div>
 {<div className="scene-controls forecast-controls"><p className="forecast-selected-day">{dayLabel(moment)}</p><label htmlFor="forecast-hour">TIME IN NEW YORK <span>{forecast?timeLabel(moment):`Now · ${timeLabel(moment)}`}</span></label><input id="forecast-hour" type="range" min="0" max={Math.max(0,dayTimes.length-1)} step="1" value={hourIndex} disabled={!usable||dayTimes.length<2} aria-valuetext={usable?`${forecast?'':'Now, '}${dayLabel(moment)}, ${timeLabel(moment)}`:'No forecast hour available'} onChange={e=>chooseHour(Number(e.target.value))}/><div className="range-labels"><span>{date===today?'Now':dayTimes[0]?timeLabel(dayTimes[0]):''}</span><span>{dayTimes.length>1?timeLabel(dayTimes.at(-1)!):''}</span></div><div className="forecast-hour-buttons"><button disabled={!dayTimes.length||hourIndex===0} onClick={()=>chooseHour(hourIndex-1)}>← Earlier</button><button disabled={!dayTimes.length||hourIndex>=dayTimes.length-1} onClick={()=>chooseHour(hourIndex+1)}>Later →</button></div>{chosen&&<div className="forecast-fact"><span>PRECIPITATION CHANCE</span><strong>{chosen.precipitationProbability===null?'Not available':`${chosen.precipitationProbability}%`}</strong></div>}</div>}
 {solarDay&&<div className="solar-times"><span>Sunrise <strong>{timeLabel(solarDay.sunrise)}</strong></span><span>Sunset <strong>{timeLabel(solarDay.sunset)}</strong></span></div>}
 <p className="window-note" role="status">{!usable?weatherError||stale?'Weather is temporarily unavailable. The neutral illustration is not a current weather report.':'Loading the latest weather and hourly forecast.':forecast?'The scene follows the forecast for the selected hour. Predictions can change, especially farther ahead.':'Current New York conditions shape this East River panorama. Choose a day or move the time slider to look ahead.'}</p></aside></div>
 <p className="source-note">Original pixel artwork · {forecast?'Hourly forecast':'Current model conditions'}{usable?` · Retrieved ${timeLabel(usable.fetchedAt)}`:''} · All dates and times in New York · <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather: Open-Meteo <ArrowUpRight size={10}/></a></p></>;
}

function ForecastIcon({code}:{code:number|null|undefined}){if(code==null)return <span>—</span>;if(code===1||code===2)return <CloudSun size={28}/>;const sky=skyFor(code);return sky==='Clear'?<Sun size={28}/>:sky==='Rain'?<CloudRain size={28}/>:sky==='Snow'?<Snowflake size={28}/>:sky==='Fog'?<CloudFog size={28}/>:sky==='Storm'?<CloudLightning size={28}/>:<Cloud size={28}/>;}
