import {useEffect,useState} from 'react';
import {ArrowDown,ArrowUp,RefreshCw,Radio,Info,TrainFront,ChevronDown,ChevronUp} from 'lucide-react';
import {COLORS,HUBS,ROUTES,displayDirection,type ArrivalResponse,type Direction,type Route} from '../data/transit';
import MapBase from './MapBase';
import {ROUTE_TRACES,pixelPath,tracePoints} from '../data/routePaths';
import '../neighborhoodFrames.css';
export function Badge({route,small=false}:{route:Route;small?:boolean}){return <span className={`route-badge ${small?'small':''}`} style={{background:COLORS[route]}}>{route}</span>;}
function HubMap({selected,route,onSelect}:{selected:string;route:Route|null;onSelect:(id:string)=>void}){
 return <div className="map-scroll neighborhood-scroll"><svg className="hub-map neighborhood-map" viewBox="0 0 960 870" aria-label="Ten subway neighborhoods across Manhattan, the Bronx, Queens, and Brooklyn">
 <rect width="960" height="870" fill="#111714"/><g transform="translate(100 15) scale(1.05)"><MapBase labels={false}/></g>
 {route&&<g key={route} className="route-trace" data-route={route} aria-hidden="true" pointerEvents="none">{ROUTE_TRACES[route].paths.map((path,index)=>{const points=tracePoints(path);const d=pixelPath(points);return <g key={index}><path d={d} fill="none" stroke="#101412" strokeWidth="11"/><path className="route-trace-line" d={d} fill="none" stroke={COLORS[route]} strokeWidth="4" strokeLinejoin="miter"/>{[points[0],points[points.length-1]].map(([x,y],i)=><rect key={i} x={x-4} y={y-4} width="8" height="8" fill="#111714" stroke={COLORS[route]} strokeWidth="2"/>)}</g>;})}</g>}
 <g aria-hidden="true" fill="#778c7b" fontSize="10" letterSpacing="3"><text x="425" y="44">THE BRONX</text><text x="547" y="203">QUEENS</text><text x="391" y="683">BROOKLYN</text><text x="310" y="357" transform="rotate(-65 310 357)">MANHATTAN</text></g>
 {HUBS.map((h,index)=>{const active=h.id===selected;const dim=route&&!h.routes.includes(route);const markerColor=route&&h.routes.includes(route)?COLORS[route]:active?'#cde2b8':'#c1c4ad';const left=h.labelX<100;const bx=h.labelX,by=h.labelY;const w=252;const endX=left?bx+w:bx-10,endY=by+20;const extra=h.routes.length>8?23:0;const frameX=bx-14,frameY=by-27,frameW=260,frameH=98+extra,corner=14;const framePath=`M${frameX} ${frameY+corner}V${frameY}H${frameX+corner} M${frameX+frameW-corner} ${frameY}H${frameX+frameW}V${frameY+corner} M${frameX} ${frameY+frameH-corner}V${frameY+frameH}H${frameX+corner} M${frameX+frameW-corner} ${frameY+frameH}H${frameX+frameW}V${frameY+frameH-corner}`;return <g key={h.id} role="button" tabIndex={0} aria-label={`${h.name}, ${h.borough}, routes ${h.routes.join(', ')}`} aria-pressed={active} onClick={()=>onSelect(h.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(h.id);}}} className={`map-hub ${active?'selected':''} ${dim?'dimmed':''}`}>
 <path className="label-leader" d={`M${h.x} ${h.y} L${left?h.x-28:h.x+28} ${endY} H${endX}`} fill="none" stroke={active?'#b5d5a9':'#607066'} strokeWidth="1" strokeDasharray={active?undefined:"2 4"}/>
 <rect x={h.x-24} y={h.y-24} width="48" height="48" fill="transparent"/>
 <circle className="marker-halo" cx={h.x} cy={h.y} r="17" fill="none" stroke={markerColor} strokeWidth="1"/><path className="marker-focus" d={`M${h.x-15} ${h.y-21}h-6v6 M${h.x+15} ${h.y-21}h6v6 M${h.x-15} ${h.y+21}h-6v-6 M${h.x+15} ${h.y+21}h6v-6`} fill="none" stroke="#e5e3c9" strokeWidth="2"/>
 <rect x={h.x-9} y={h.y-9} width="18" height="18" fill="#111714" stroke={markerColor} strokeWidth="2"/>
 <rect x={h.x-4} y={h.y-4} width="8" height="8" fill={route&&!dim?markerColor:active?'#cde2b8':'#7d8876'}/>
 <rect className="label-background" x={bx-10} y={by-22} width={w} height={89+extra} fill="#111714" opacity=".96"/>
 <path className="neighborhood-frame" d={framePath} fill="none"/>
 <text x={bx} y={by-5} fill="#8c9a8d" fontSize="9" letterSpacing="1.3">{String(index+1).padStart(2,'0')} / {h.borough.toUpperCase()}</text>
 <rect className="neighborhood-accent" x={bx-10} y={by+3} width="3" height="15" fill="#b8d3a5"/><text className="neighborhood-name" x={bx} y={by+16} fill={active?'#e9ebcd':'#d0d2be'} fontSize="15" fontWeight="500">{h.shortName}</text>
 {h.routes.map((r,i)=><g key={r} transform={`translate(${bx+(i%8)*24},${by+28+Math.floor(i/8)*23})`} opacity={route && route!==r ? .3 : 1}><rect width="19" height="19" fill={COLORS[r]}/><text x="9.5" y="13.5" textAnchor="middle" fill="#151a16" fontSize="12" fontWeight="500">{r}</text></g>)}
 <text x={bx} y={by+62+extra} fill="#99aa92" fontSize="9">{h.stations.length} {h.stations.length===1?'STATION COMPLEX':'NEARBY STATIONS'} · EXPLORE →</text>
 </g>;})}
 <text x="25" y="849" fill="#8f9f87" fontSize="9" letterSpacing="1">SCHEMATIC / INTERMEDIATE STOPS OMITTED</text>
 </svg></div>;
}
export default function Subway(){
 const [selected,setSelected]=useState('times-square');const [station,setStation]=useState('all');const [route,setRoute]=useState<Route|null>(null);const [response,setResponse]=useState<ArrivalResponse|null>(null);const [loading,setLoading]=useState(false);const [failed,setFailed]=useState(false);const [retry,setRetry]=useState(0);const [now,setNow]=useState(Date.now()/1000);const [expanded,setExpanded]=useState(false);
 const hub=HUBS.find(h=>h.id===selected)!;
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()/1000),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{setExpanded(false);},[selected,route,station]);
 useEffect(()=>{let disposed=false;let controller:AbortController|undefined;setResponse(null);setFailed(false);setLoading(true);
 async function load(){controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),15000);try{const r=await fetch(`/api/arrivals?hub=${selected}`,{signal:controller.signal});if(!r.ok)throw new Error('Feed unavailable');const data=await r.json() as ArrivalResponse;if(data.hubId!==selected||!Array.isArray(data.arrivals)||!['live','partial','unavailable'].includes(data.status))throw new Error('Invalid response');if(!disposed){setResponse(data);setFailed(false);}}catch{if(!disposed)setFailed(true);}finally{clearTimeout(timeout);if(!disposed)setLoading(false);}}
 void load();const t=setInterval(()=>{if(document.visibilityState==='visible')void load();},30000);return()=>{disposed=true;controller?.abort();clearInterval(t);};},[selected,retry]);
 const old=!!response?.updatedAt&&now-response.updatedAt>180;const unavailable=failed||old||response?.status==='unavailable';const data=unavailable?[]:(response?.arrivals??[]).filter(a=>a.time>=now-15);
 const pending=loading||((!response||response.hubId!==selected)&&!failed);
 const rows=data.filter(a=>(!route||a.route===route)&&(station==='all'||a.stationId===station));const age=response?.updatedAt?Math.max(0,Math.floor(now-response.updatedAt)):0;
 function select(id:string){setSelected(id);setStation('all');if(route&&!HUBS.find(h=>h.id===id)!.routes.includes(route))setRoute(null);}
 function filter(r:Route){setStation('all');if(route===r){setRoute(null);return;}setRoute(r);if(!hub.routes.includes(r))setSelected(HUBS.find(h=>h.routes.includes(r))!.id);}
 return <><div className="project-heading"><div><h2>The Underground<span className="heading-dot">.</span></h2><p className="project-description">Live arrivals across ten neighborhoods.</p></div></div>
 <div className="route-directory"><div><p className="eyebrow">FIND YOUR LINE</p></div><div className="route-buttons"><button className={`route-all ${!route?'active':''}`} onClick={()=>setRoute(null)} aria-pressed={!route}>ALL</button>{ROUTES.map(r=><button key={r} className={`badge-button ${route===r?'chosen':''}`} aria-label={`Highlight ${r} route hubs`} aria-pressed={route===r} onClick={()=>filter(r)}><Badge route={r}/></button>)}</div></div>
 <div className="transit-workbench"><div className="map-panel"><div className="map-toolbar"><span><span className="status-dot"/> NYC / NEIGHBORHOODS</span><span className="map-count">10 NEIGHBORHOODS <span className="muted">/</span> 04 BOROUGHS</span></div>{route&&<div className="route-map-summary" aria-live="polite"><><Badge route={route}/><div><strong>{ROUTE_TRACES[route].name}</strong><p>{ROUTE_TRACES[route].termini}</p></div><button className="clear-route" onClick={()=>setRoute(null)} aria-label="Clear highlighted route">Clear ×</button></></div>}<HubMap selected={selected} route={route} onSelect={select}/><div className="map-caption"><span><span className="legend-square"/> CLICK A NEIGHBORHOOD</span><span>{route?`${route} / SIMPLIFIED ROUTE`:'22 ROUTES · NO SHUTTLES'}</span></div>{route&&<p className="route-trace-note">Regular-service schematic; temporary reroutes are not shown. {ROUTE_TRACES[route].note}</p>}</div>
 <aside className="arrival-panel" aria-label="Selected neighborhood arrivals"><div className="station-intro"><p className="eyebrow"><TrainFront size={13}/> SELECTED NEIGHBORHOOD <span className="station-index">{String(HUBS.indexOf(hub)+1).padStart(2,'0')} / {String(HUBS.length).padStart(2,'0')}</span></p><h3>{hub.name}</h3><span className="station-borough">{hub.borough} · {hub.stations.length} {hub.stations.length===1?'station complex':'nearby stations'}</span><div className="station-routes"><button className={`all-chip ${!route?'selected':''}`} aria-pressed={!route} onClick={()=>setRoute(null)}>All</button>{hub.routes.map(r=><button key={r} className={`badge-button ${route===r?'chosen':''}`} aria-label={`Show ${r} train arrivals`} aria-pressed={route===r} onClick={()=>filter(r)}><Badge route={r}/></button>)}</div>
 <div className="boarding-filter"><label htmlFor="boarding-station">BOARD AT</label><select id="boarding-station" value={station} onChange={e=>{const next=e.target.value;setStation(next);if(next!=='all'&&route&&!hub.stations.find(s=>s.id===next)!.routes.includes(route))setRoute(null);}}><option value="all">All {hub.stations.length} {hub.stations.length===1?'station':'stations'} in this neighborhood</option>{hub.stations.map(s=><option key={s.id} value={s.id}>{s.name} · {s.routes.join(' ')}</option>)}</select></div>
 <details className="neighborhood-stations"><summary>Stations &amp; estimated walks</summary><p className="walk-anchor">From {hub.stations[0].name}. Street-walk estimates, not your location; allow extra time for entrances and signals.</p><ul>{hub.stations.map(s=><li key={s.id}><button aria-pressed={station===s.id} onClick={()=>{setStation(s.id);if(route&&!s.routes.includes(route))setRoute(null);}}><span>{s.name}</span><small>{s.walkMinutes===0?'ANCHOR':`~${s.walkMinutes} MIN WALK`}</small></button><span className="mini-routes">{s.routes.map(r=><Badge key={r} route={r} small/>)}</span></li>)}</ul><p className="walk-anchor">Separate stations may require exiting and paying another fare. Walking times are approximate, not turn-by-turn directions.</p></details>
 </div>
 <div className={`data-status ${unavailable?'warning':''}`} role="status"><span className={`status-dot ${unavailable?'offline':''}`}/>{pending?'CONNECTING TO MTA':unavailable?'LIVE UPDATES UNAVAILABLE':response?.status==='partial'?'PARTIAL LIVE DATA':'LIVE MTA PREDICTIONS'}{<button className="icon-button" aria-label="Refresh arrivals" onClick={()=>setRetry(v=>v+1)} disabled={pending}><RefreshCw size={13} className={pending?'spinning':''}/></button>}</div>
 <div className="arrival-content" aria-busy={pending}>
 {pending?<div className="arrival-loading"><div/><div/><div/><p>Checking the next trains…</p></div>:unavailable?<div className="empty-state"><Radio size={24}/><h4>Live arrivals unavailable.</h4><p>{response?.message??'We couldn’t reach fresh MTA predictions. Please try again.'}</p><button className="outline-button" onClick={()=>setRetry(v=>v+1)}>Try again <RefreshCw size={14}/></button></div>:(['N','S'] as Direction[]).map(dir=>{const group=rows.filter(a=>displayDirection(a,hub)===dir);return <section className="direction-group" key={dir}><h4>{dir==='N'?<ArrowUp size={12}/>:<ArrowDown size={12}/>} {route==='G' ? (dir==='N'?'Towards Court Sq':'Towards Church Av') : route==='L' ? (dir==='N'?'Towards 8 Av':'Towards Brooklyn') : route==='J'||route==='Z' ? (dir==='N'?'Towards Manhattan':'Towards Queens') : route==='7' ? (dir==='N'?'Towards Flushing':'Towards Hudson Yards') : hub.directions[dir]}</h4>{group.length===0?<p className="no-arrivals">No upcoming predictions for this direction.</p>:group.slice(0,expanded?30:4).map(a=>{const min=Math.max(0,Math.ceil((a.time-now)/60));return <div className="arrival-row" key={a.id}><Badge route={a.route}/><div><span>{a.destination}</span><small className="arrival-station">{a.stationName}{a.express?' · Express':''}</small></div><strong>{min===0?'Due':min}<small>{min>0?'min':''}</small></strong></div>;})}</section>;})}
 {!pending&&!unavailable&&rows.length>8&&<button className="show-more" onClick={()=>setExpanded(!expanded)}>{expanded?'Show fewer':'Show more arrivals'} {expanded?<ChevronUp size={13}/>:<ChevronDown size={13}/>}</button>}
 </div><div className="panel-footnote"><Info size={13}/><p>{pending?'Checking for fresh predictions.':unavailable?'Use official MTA information to plan your trip.':`Feed updated ${age<60?`${age}s`:`${Math.floor(age/60)}m`} ago. ETAs exclude walking time.`}</p></div><details className="station-details"><summary>About this neighborhood</summary><p>{hub.note}</p>{response?.status==='partial'&&<p>{response.message}</p>}<a href="https://www.mta.info/" target="_blank" rel="noreferrer">Official MTA information ↗</a></details>
 </aside></div>
<p className="source-note">Original schematic · Ten curated neighborhoods, not a complete travel map · {<a href="https://www.mta.info/developers" target="_blank" rel="noreferrer">Data: MTA ↗</a>} · S services excluded</p></>;
}
